### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by elliot-huffman** [TfT-02/DynamicTextures#7]
Can you add support to change back to the default resource pack?

E.G. tp-ing back to the main world changes back to default

This would eliminate the need to relog and keep more clients on the server.

**Comment by leodutra** [comment]
Please, tell it's **technically impossible** on plugin info.
Thought it was possible and discovered by analysis that it is not an _unimplemented_ feature.

Thanks for the great plugin and Multiverse integration!
Best regards
